### ISSUE TITLE
Página consulta: Definições

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [Marcelo-Theodoro/web2clinic#18]
Definir: 

- O que acontecer quando clica no botão "gravar"

- Diagnóstico

- Atestado

- Prescrição médica

**Comment by Marcelo-Theodoro** [comment]
- Botão consultas: Redirecionar para a página do paciente.

**Comment by lucasm310** [comment]
Ao clicar em gravar vai ser redirecionado para a pagina ver_consulta onde lá vai ser gerado o prontuario, atestado e prescrição médica.
