### ISSUE TITLE
Fazer o modulo de atestados

### ISSUE THREAD

**Issue by lucasm310** [Marcelo-Theodoro/web2clinic#23]

**Comment by Marcelo-Theodoro** [comment]
- Criar base em PDF contendo:  informações da clínica, informações do médico, e a data.

- Criar VirutalField com o texto:
"Declaro que {{paciente.nome}}, esteve aos meus cuidados profissionais, enquandrando-se no CID:__________, necessitando de __________  de repouso."

**Comment by Marcelo-Theodoro** [comment]
Controller preparado no commit 1e0ad5c, falta apenas layout, botão para imprimir e fechar a issue.

**Comment by lucasm310** [comment]
Falta deixar o padrão 
"Declaro que {{paciente.nome}}, esteve aos meus cuidados profissionais, enquandrando-se no CID:__________, necessitando de __________ de repouso."

**Comment by lucasm310** [comment]
Commit f62d3f51f08d5666ff57e43032bfa874271ee60c deixa padrão o layout e insere a impressão
